embedding:
  batch_size: 32
  device: auto
  model_name: auto
graph:
  cache_enabled: true
  unified_graph_path: ./graphs/unified/unified_knowledge_graph.json
  vector_store_path: ./graphs/embeddings
llm:
  device_map: auto
  max_new_tokens: 2048
  model_path: /DATA/MODELS/models--meta-llama--Llama-3.1-8B-Instruct
  provider: huggingface_local
  temperature: 0.1
  torch_dtype: bfloat16
qa:
  chain_type: retrieval_qa
  enable_memory: false
  max_docs: 10
  min_relevance_score: 0.3
system:
  log_level: INFO
  max_workers: 4
  verbose: false
